CREATE TABLE appreciates
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    TEXT                                    NOT NULL,
    rating     INTEGER                                 NOT NULL,
    room_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_appreciates PRIMARY KEY (id)
);

CREATE TABLE banks
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bank_name          VARCHAR(255)                            NOT NULL,
    account_number     VARCHAR(255)                            NOT NULL,
    owner_bank_account VARCHAR(255),
    user_id            BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_banks PRIMARY KEY (id)
);

CREATE TABLE bookings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id      BIGINT                                  NOT NULL,
    guest_id     BIGINT                                  NOT NULL,
    start_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    total_amount DECIMAL                                 NOT NULL,
    rate_per_day DECIMAL                                 NOT NULL,
    paid_at      TIMESTAMP WITHOUT TIME ZONE,
    expire_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE contact
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_contact        VARCHAR(255)                            NOT NULL,
    phone_number_contact VARCHAR(255)                            NOT NULL,
    address_contact      VARCHAR(255)                            NOT NULL,
    company_name         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE coupon_histories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id BIGINT                                  NOT NULL,
    coupon_id  BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    used_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_coupon_histories PRIMARY KEY (id)
);

CREATE TABLE coupon_mails
(
    coupon_id BIGINT NOT NULL,
    mail_id   BIGINT NOT NULL,
    CONSTRAINT pk_coupon_mails PRIMARY KEY (coupon_id, mail_id)
);

CREATE TABLE coupons
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                VARCHAR(255)                            NOT NULL,
    description         TEXT                                    NOT NULL,
    discount_percentage INTEGER                                 NOT NULL,
    min_amount_apply    DECIMAL(12),
    max_discount_amount DECIMAL(12),
    start_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expire_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status              SMALLINT                                NOT NULL,
    quantity            INTEGER                                 NOT NULL,
    used_quantity       INTEGER,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_coupons PRIMARY KEY (id)
);

CREATE TABLE events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_name        VARCHAR(255)                            NOT NULL,
    event_description TEXT                                    NOT NULL,
    poster_url_path   VARCHAR(255)                            NOT NULL,
    event_url_path    VARCHAR(255)                            NOT NULL,
    start_at          TIMESTAMP WITHOUT TIME ZONE,
    end_at            TIMESTAMP WITHOUT TIME ZONE,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE landlords
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_landlord        TEXT                                    NOT NULL,
    description_landlord TEXT                                    NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_landlords PRIMARY KEY (id)
);

CREATE TABLE locations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country         VARCHAR(255),
    city            VARCHAR(255),
    province        VARCHAR(255),
    district        VARCHAR(255),
    address_details VARCHAR(255),
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE mails
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_title   VARCHAR(255),
    email_author  VARCHAR(255),
    email_content VARCHAR(255),
    email_status  VARCHAR(255)                            NOT NULL,
    email_type    VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_mails PRIMARY KEY (id)
);

CREATE TABLE notions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    content    TEXT                                    NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_notions PRIMARY KEY (id)
);

CREATE TABLE payment_histories
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount         DECIMAL                                 NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    payment_id     BIGINT                                  NOT NULL,
    payment_status VARCHAR(255),
    description    TEXT,
    note           VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment_histories PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount           DECIMAL                                 NOT NULL,
    payment_method   VARCHAR(255)                            NOT NULL,
    payment_provider VARCHAR(255)                            NOT NULL,
    payment_status   VARCHAR(255)                            NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    booking_id       BIGINT                                  NOT NULL,
    payment_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name   VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE room_booking_services
(
    booking_service_id BIGINT NOT NULL,
    room_id            BIGINT NOT NULL,
    CONSTRAINT pk_room_booking_services PRIMARY KEY (booking_service_id, room_id)
);

CREATE TABLE room_images
(
    room_id   BIGINT       NOT NULL,
    image_url VARCHAR(255) NOT NULL
);

CREATE TABLE rooms
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_name    TEXT                                    NOT NULL,
    description  TEXT                                    NOT NULL,
    room_code    VARCHAR(255)                            NOT NULL,
    location_id  BIGINT                                  NOT NULL,
    area         INTEGER                                 NOT NULL,
    price        DECIMAL(12)                             NOT NULL,
    is_available VARCHAR(255)                            NOT NULL,
    landlord_id  BIGINT                                  NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE standards
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_service VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    unit         VARCHAR(255)                            NOT NULL,
    price        DECIMAL                                 NOT NULL,
    status       VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_standards PRIMARY KEY (id)
);

CREATE TABLE user_mails
(
    mail_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_mails PRIMARY KEY (mail_id, user_id)
);

CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name            VARCHAR(255),
    username             VARCHAR(20)                             NOT NULL,
    password             VARCHAR(255),
    user_status          VARCHAR(255)                            NOT NULL,
    email                VARCHAR(255),
    role_id              BIGINT                                  NOT NULL,
    provider             VARCHAR(255)                            NOT NULL,
    provider_id          VARCHAR(255),
    avatar_url           VARCHAR(255),
    balance              DECIMAL(20)                             NOT NULL,
    identity_card        VARCHAR(12),
    phone_number         VARCHAR(255),
    favorite_landlord_id BIGINT,
    coins                INTEGER                                 NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE withdraws
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bank_name          VARCHAR(255),
    account_number     VARCHAR(255),
    owner_bank_account VARCHAR(255),
    bank_content       TEXT,
    amount             DECIMAL(19)                             NOT NULL,
    withdraw_status    VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_withdraws PRIMARY KEY (id)
);

ALTER TABLE coupon_histories
    ADD CONSTRAINT uc_87ea397103cb6f9fcd077ef67 UNIQUE (coupon_id, user_id);

ALTER TABLE banks
    ADD CONSTRAINT uc_banks_user UNIQUE (user_id);

ALTER TABLE coupons
    ADD CONSTRAINT uc_coupons_code UNIQUE (code);

ALTER TABLE landlords
    ADD CONSTRAINT uc_landlords_user UNIQUE (user_id);

ALTER TABLE payment_histories
    ADD CONSTRAINT uc_payment_histories_payment UNIQUE (payment_id);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_booking UNIQUE (booking_id);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_rolename UNIQUE (role_name);

ALTER TABLE rooms
    ADD CONSTRAINT uc_rooms_location UNIQUE (location_id);

ALTER TABLE rooms
    ADD CONSTRAINT uc_rooms_roomcode UNIQUE (room_code);

ALTER TABLE rooms
    ADD CONSTRAINT uc_rooms_roomname UNIQUE (room_name);

ALTER TABLE standards
    ADD CONSTRAINT uc_standards_nameservice UNIQUE (name_service);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_identitycard UNIQUE (identity_card);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE appreciates
    ADD CONSTRAINT FK_APPRECIATES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE appreciates
    ADD CONSTRAINT FK_APPRECIATES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE banks
    ADD CONSTRAINT FK_BANKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_GUEST FOREIGN KEY (guest_id) REFERENCES users (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE coupon_histories
    ADD CONSTRAINT FK_COUPON_HISTORIES_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE coupon_histories
    ADD CONSTRAINT FK_COUPON_HISTORIES_ON_COUPON FOREIGN KEY (coupon_id) REFERENCES coupons (id);

ALTER TABLE coupon_histories
    ADD CONSTRAINT FK_COUPON_HISTORIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE landlords
    ADD CONSTRAINT FK_LANDLORDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payment_histories
    ADD CONSTRAINT FK_PAYMENT_HISTORIES_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payments (id);

ALTER TABLE payment_histories
    ADD CONSTRAINT FK_PAYMENT_HISTORIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_LANDLORD FOREIGN KEY (landlord_id) REFERENCES landlords (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_FAVORITE_LANDLORD FOREIGN KEY (favorite_landlord_id) REFERENCES landlords (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE coupon_mails
    ADD CONSTRAINT fk_coumai_on_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id);

ALTER TABLE coupon_mails
    ADD CONSTRAINT fk_coumai_on_mail FOREIGN KEY (mail_id) REFERENCES mails (id);

ALTER TABLE room_booking_services
    ADD CONSTRAINT fk_roobooser_on_booking_service FOREIGN KEY (booking_service_id) REFERENCES standards (id);

ALTER TABLE room_booking_services
    ADD CONSTRAINT fk_roobooser_on_room FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE room_images
    ADD CONSTRAINT fk_room_images_on_room FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE user_mails
    ADD CONSTRAINT fk_usemai_on_mail FOREIGN KEY (mail_id) REFERENCES mails (id);

ALTER TABLE user_mails
    ADD CONSTRAINT fk_usemai_on_user FOREIGN KEY (user_id) REFERENCES users (id);

DROP SEQUENCE appreciates_id_seq CASCADE;

DROP SEQUENCE banks_id_seq CASCADE;

DROP SEQUENCE bookings_id_seq CASCADE;

DROP SEQUENCE contact_id_seq CASCADE;

DROP SEQUENCE coupon_histories_id_seq CASCADE;

DROP SEQUENCE coupons_id_seq CASCADE;

DROP SEQUENCE events_id_seq CASCADE;

DROP SEQUENCE landlords_id_seq CASCADE;

DROP SEQUENCE locations_id_seq CASCADE;

DROP SEQUENCE mails_id_seq CASCADE;

DROP SEQUENCE notions_id_seq CASCADE;

DROP SEQUENCE payment_histories_id_seq CASCADE;

DROP SEQUENCE payments_id_seq CASCADE;

DROP SEQUENCE roles_id_seq CASCADE;

DROP SEQUENCE rooms_id_seq CASCADE;

DROP SEQUENCE standards_id_seq CASCADE;

DROP SEQUENCE users_id_seq CASCADE;

DROP SEQUENCE withdraws_id_seq CASCADE;

-- Add more changes below this line -- 
-- Insert ADMIN and USER roles, ignore if role_name already exists
INSERT INTO roles (role_name, description, created_at, updated_at)
VALUES
  ('ADMIN', 'Administrator', now(), now()),
  ('USER',  'Regular user', now(), now())
ON CONFLICT (role_name) DO NOTHING;

